### ISSUE TITLE
Type Error on Node 8

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/enable-travis#2]
Coming from `git-repo-name`

```
/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/enable-travis/node_modules/git-repo-name/index.js:20
    cb(null, utils.filename(segments.pop()));
    ^

TypeError: cb is not a function
```

Want to submit it here as remainder. Do you want PRs around? It seems `sync-travis` not work too.

**Comment by doowb** [comment]
> Do you want PRs around?

That'd be awesome!

Seems like this one just needs to use the `.sync` method from `git-repo-name`.
